# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
print("NumPy Version:", np.__version__)

print("NumPy Configuration:")
np.show_config()

NumPy Version: 2.4.6
NumPy Configuration:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/pc/anaconda3/Library/include
    lib directory: C:/Users/pc/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\Users\task_178034591152523\croot\numpy_and_numpy_base_1780346079294\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/pc/anaconda3/Library/include
    lib directory: C:/Users/pc/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\Users\task_178034591152523\croot\numpy_and_numpy_base_1780346079294\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.44.35227
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.44.35227
  cython:
    commands:

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
#method 1

rng = np.random.default_rng()
# Generate continuous uniform random values between 0.0 and 1.0
a = rng.random((2, 3, 5))
print(a)

#method 2

a = np.random.random((2, 3, 5))
print(a)

#method 3

a = np.random.rand(2, 3, 5)
print(a)

#method 4

a = np.random.uniform(low=0.0, high=1.0, size=(2, 3, 5))
print(a)

[[[0.10418636 0.33661569 0.00602486 0.89431439 0.29821131]
  [0.05947227 0.62702649 0.34531265 0.13364129 0.79128652]
  [0.13774691 0.05043553 0.60527444 0.75866435 0.22908926]]

 [[0.74163669 0.3600057  0.65000201 0.99023667 0.96068395]
  [0.98957601 0.40320896 0.14296296 0.27114496 0.32999011]
  [0.77438592 0.66320273 0.57888675 0.62867077 0.81350821]]]
[[[0.60833398 0.3240482  0.37806912 0.74625709 0.26374381]
  [0.07599762 0.25185572 0.85239632 0.69321896 0.20375096]
  [0.58203751 0.57077025 0.67541855 0.81085947 0.42270897]]

 [[0.45747717 0.91353611 0.22364752 0.00947073 0.69982027]
  [0.91826528 0.48400148 0.91327188 0.89507579 0.48160632]
  [0.02677473 0.07122466 0.09576978 0.31078548 0.34650819]]]
[[[0.58863016 0.39681634 0.01556124 0.72524961 0.09668284]
  [0.62250076 0.73855485 0.20842943 0.84810144 0.85722502]
  [0.79811332 0.82786993 0.44930844 0.59699754 0.93917191]]

 [[0.82301234 0.04945996 0.14348618 0.67092871 0.23447577]
  [0.95240402 0.95575953 0.64749117 0.95191338


### 4. Print a.


In [4]:
print(a)

[[[0.447566   0.50451345 0.38410278 0.78644621 0.04320063]
  [0.69581644 0.37856242 0.01575249 0.03933754 0.70712244]
  [0.21063205 0.50497537 0.40808776 0.18240463 0.19004262]]

 [[0.16317696 0.08031159 0.9659948  0.77199403 0.29735399]
  [0.18490007 0.70468937 0.29213093 0.73857402 0.42024524]
  [0.79979957 0.71266438 0.61904777 0.68894208 0.47976009]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [5]:
b = np.ones((5, 2, 3))


### 6. Print b.


In [6]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [7]:
print(f"Size of a: {a.size}")  # Output: 30
print(f"Size of b: {b.size}")  # Output: 30
print(f"Do they have the same total size? {a.size == b.size}")

Size of a: 30
Size of b: 30
Do they have the same total size? True



### 8. Are you able to add a and b? Why or why not?


we are not able to add a and b because they should have the exact same shape.



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [8]:
c = b.reshape(a.shape)
print (c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [10]:
d = a + c
print(d)
print(f"Shape of a: {a.shape}")
print(f"Shape of c: {c.shape}")  
print(f"Do they have the same shape? {a.shape == c.shape}")

[[[1.447566   1.50451345 1.38410278 1.78644621 1.04320063]
  [1.69581644 1.37856242 1.01575249 1.03933754 1.70712244]
  [1.21063205 1.50497537 1.40808776 1.18240463 1.19004262]]

 [[1.16317696 1.08031159 1.9659948  1.77199403 1.29735399]
  [1.18490007 1.70468937 1.29213093 1.73857402 1.42024524]
  [1.79979957 1.71266438 1.61904777 1.68894208 1.47976009]]]
Shape of a: (2, 3, 5)
Shape of c: (2, 3, 5)
Do they have the same shape? True



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [13]:
print(a)
print(d)

[[[0.447566   0.50451345 0.38410278 0.78644621 0.04320063]
  [0.69581644 0.37856242 0.01575249 0.03933754 0.70712244]
  [0.21063205 0.50497537 0.40808776 0.18240463 0.19004262]]

 [[0.16317696 0.08031159 0.9659948  0.77199403 0.29735399]
  [0.18490007 0.70468937 0.29213093 0.73857402 0.42024524]
  [0.79979957 0.71266438 0.61904777 0.68894208 0.47976009]]]
[[[1.447566   1.50451345 1.38410278 1.78644621 1.04320063]
  [1.69581644 1.37856242 1.01575249 1.03933754 1.70712244]
  [1.21063205 1.50497537 1.40808776 1.18240463 1.19004262]]

 [[1.16317696 1.08031159 1.9659948  1.77199403 1.29735399]
  [1.18490007 1.70468937 1.29213093 1.73857402 1.42024524]
  [1.79979957 1.71266438 1.61904777 1.68894208 1.47976009]]]


we can notice that every single value in array d is exactly 1 greater than its corresponding value in array a
 d = a + 1
because in the nend c is a reshape of be and b is an all ones array


### 12. Multiply a and c. Assign the result to e.


In [14]:
e = a * c
print("Shape of e:", e.shape)
print(e)

Shape of e: (2, 3, 5)
[[[0.447566   0.50451345 0.38410278 0.78644621 0.04320063]
  [0.69581644 0.37856242 0.01575249 0.03933754 0.70712244]
  [0.21063205 0.50497537 0.40808776 0.18240463 0.19004262]]

 [[0.16317696 0.08031159 0.9659948  0.77199403 0.29735399]
  [0.18490007 0.70468937 0.29213093 0.73857402 0.42024524]
  [0.79979957 0.71266438 0.61904777 0.68894208 0.47976009]]]




### 13. Does e equal to a? Why or why not?


In [15]:
print(np.array_equal(e, a))

True


every item form c is equal to 1
then we have identity mutiplication



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [16]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(f"d_max:  {d_max}")
print(f"d_min:  {d_min}")
print(f"d_mean: {d_mean}")


d_max:  1.9659947984852177
d_min:  1.0157524870548467
d_mean: 1.4472715910881995



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [17]:
f = np.empty(d.shape)

print("Shape of f:", f.shape)

Shape of f: (2, 3, 5)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [18]:
for i in range(d.shape[0]):        
    for j in range(d.shape[1]):    
        for k in range(d.shape[2]):
            val = d[i, j, k]
            
            # 1. If it equals d_min, assign 0
            if val == d_min:
                f[i, j, k] = 0
                
            # 2. If it's larger than d_min but smaller than d_mean, assign 25
            elif d_min < val < d_mean:
                f[i, j, k] = 25
                
            # 3. If it equals d_mean, assign 50
            elif val == d_mean:
                f[i, j, k] = 50
                
            # 4. If it's larger than d_mean but smaller than d_max, assign 75
            elif d_mean < val < d_max:
                f[i, j, k] = 75
                
            # 5. If it equals d_max, assign 100
            elif val == d_max:
                f[i, j, k] = 100

print(f)


[[[ 75.  75.  25.  75.  25.]
  [ 75.  25.   0.  25.  75.]
  [ 25.  75.  25.  25.  25.]]

 [[ 25.  25. 100.  75.  25.]
  [ 25.  75.  25.  75.  25.]
  [ 75.  75.  75.  75.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [19]:
print(d)
print(f)

[[[1.447566   1.50451345 1.38410278 1.78644621 1.04320063]
  [1.69581644 1.37856242 1.01575249 1.03933754 1.70712244]
  [1.21063205 1.50497537 1.40808776 1.18240463 1.19004262]]

 [[1.16317696 1.08031159 1.9659948  1.77199403 1.29735399]
  [1.18490007 1.70468937 1.29213093 1.73857402 1.42024524]
  [1.79979957 1.71266438 1.61904777 1.68894208 1.47976009]]]
[[[ 75.  75.  25.  75.  25.]
  [ 75.  25.   0.  25.  75.]
  [ 25.  75.  25.  25.  25.]]

 [[ 25.  25. 100.  75.  25.]
  [ 25.  75.  25.  75.  25.]
  [ 75.  75.  75.  75.  75.]]]


yes we got the expected result

### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [21]:
f = np.empty(d.shape, dtype=object)
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            val = d[i, j, k]
            
            if val == d_min:
                f[i, j, k] = 'A'
            elif d_min < val < d_mean:
                f[i, j, k] = 'B'
            elif val == d_mean:
                f[i, j, k] = 'C'
            elif d_mean < val < d_max:
                f[i, j, k] = 'D'
            elif val == d_max:
                f[i, j, k] = 'E'

print(f)

[[['D' 'D' 'B' 'D' 'B']
  ['D' 'B' 'A' 'B' 'D']
  ['B' 'D' 'B' 'B' 'B']]

 [['B' 'B' 'E' 'D' 'B']
  ['B' 'D' 'B' 'D' 'B']
  ['D' 'D' 'D' 'D' 'D']]]
